#include "activity.h"
#include "deployment.h"
#include <assert.h>
#include <core/event.h>
#include <core/partition.h>
#include <core/thread.h>
#include <core/time.h>
#include <types.h>

/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
#define POK_CONFIG_NB_THREADS 11
uint32_t pok_threads[POK_CONFIG_NB_THREADS];
int main(void) {
  pok_thread_attr_t tattr;
  pok_ret_t ret;
  for(int i=0;i<10;++i){
    ret = pok_thread_attr_init(&(tattr));
    assert(!ret);
    tattr.entry = thr_job;
    tattr.deadline = (long long int)(10-i)*1000000000;
    tattr.priority = 10+i;
    tattr.period = 10000000000;
    tattr.stack_size = 4096;
    tattr.time_slice = 200;
    tattr.time_capacity = (i+1)*200;
    ret = pok_thread_create(&(pok_threads[i+1]), &(tattr));
    assert(!ret);
  }
  pok_partition_set_mode(POK_PARTITION_MODE_NORMAL);
  return (0);
}
