
#include <assert.h>
#include <core/event.h>
#include <core/lockobj.h>
#include <core/thread.h>
#include <errno.h>
#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
/*  Periodic task : thr1*/
void *thr_job(void) {
  while (1) {
  }
}

